### ISSUE TITLE
batch_size on training

### ISSUE THREAD

**Issue by haiautoup** [taotaonice/FaceShifter#17]
Hi @taotaonice ,

I try to train your model on a K80 GPU with 12GB of memory
If I use batch_size 16, the program ends with "CUDA out of memory" error
I set batch_size 6, I check the program uses more than 10GB of memory.

Could you tell me the environment you can train with batch_size 16
and could you give some hints, how can we train the model on multi GPUs, cause I have two K80 cards.

Thank you very much!

**Comment by taotaonice** [comment]
I use a Tesla V100 with 32GB of memory.
Please google "pytorch data parallel", and use syncBatchNorm instead of BatchNorm

**Comment by haiautoup** [comment]
Thank you @taotaonice !
