### ISSUE TITLE
Reconstruction loss

### ISSUE THREAD

**Issue by pasquini-dario** [taotaonice/FaceShifter#18]
Thank for sharing your code. 
The reconstruction loss implemented at:
https://github.com/taotaonice/FaceShifter/blob/376b09e4ecc97848c07c585f173d10932880f961/train_AEI.py#L123
is different from the one described in the original paper (i.e., Eq. 8).
Does this modified loss function have some advantages over the original one? Thank you.

**Comment by taotaonice** [comment]
What is the difference that you say ?
