### ISSUE TITLE
build acceleration module

### ISSUE THREAD

**Issue by haiautoup** [taotaonice/FaceShifter#22]
Hi @taotaonice 

I am building the acceleration module, things I found, point to using conda
But I do not use conda, could you give me some hints to build this module?

Thank you very much!
Hai Le

**Comment by jjandnn** [comment]
# 编译acceleration这个文件夹（首次，注意pybind11 用conda）
git clone https://github.com/pybind/pybind11
python3.7 -m pip install pytest && cd pybind11 && mkdir build && cd build && cmake .. -DDOWNLOAD_CATCH=1 && sudo make install

%cd ~/FaceShifter/acceleration/build
!cmake ..
!make

**Comment by haiautoup** [comment]
Hi @jjandnn 
I follow your guide, it seems I installed libs
[100%] Built target cuda_postprocess
But when import cuda_postprocess
ModuleNotFoundError: No module named 'cuda_postprocess'
Could you help me what need  I do next?

Thank you very much!
HaiLe

**Comment by jjandnn** [comment]
@haiautoup Are you using windows？
linux:
#!/bin/bash
pip install pytest easydict==1.7 matplotlib==3.0.2 xlib -i http://pypi.douban.com/simple --trusted-host pypi.douban.com
conda install pybind11 --yes
pip install ~/tensorflow_gpu-1.15.0-cp37-cp37m-manylinux2010_x86_64.whl
pip install ~/torch-1.4.0+cu92-cp37-cp37m-linux_x86_64.whl
pip install ~/torchvision-0.5.0+cu92-cp37-cp37m-linux_x86_64.whl
cd ~/FaceShifter


It is a .sh file.on BAIDU AI.

bash it.

Then ,

%cd ~/FaceShifter/acceleration/build
!cmake ..
!make

colab:
pip install pytest easydict==1.7 matplotlib==3.0.2 xlib
conda install pybind11 --yes

%cd ~/FaceShifter/acceleration/build
!cmake ..
!make

win:
[CMakeLists.txt](https://github.com/taotaonice/FaceShifter/files/4466050/CMakeLists.txt)
change your path in it

requirements:
g++ camke cuda cudnn pybind11 pytest.

this prgram is for after-treatment by cuda。

You don't have to. That's what the author said。

**Comment by haiautoup** [comment]
Hi @jjandnn 
I appreciate your very carefully help.
I am using ubuntu 18.
I meat, it seems I am successful in building the modules
This is my acceleration/build folder
![build](https://user-images.githubusercontent.com/61568868/79065011-994d1500-7cd7-11ea-8f29-77c27df5b0d5.png)

But when importing the module with python3
import cuda_postprocess
ModuleNotFoundError: No module named 'cuda_postprocess'
May be I need a minor step to make python3 to recognize the module

Thank you very much!
Hai Le

**Comment by haiautoup** [comment]
It is Ok now!
I forgot make install
Thank you @jjandnn

**Comment by jjandnn** [comment]
:)
