### ISSUE TITLE
About the Discriminator?

### ISSUE THREAD

**Issue by menggui1993** [taotaonice/FaceShifter#24]
First, thanks for your great work. I have a question about the discriminator. 
In the paper, the author said they used the same multi scale discriminator as the StyleGAN. But I think StyleGAN doesn't use a multi scale discriminator. 
In your implementation, you seems to use the multi scale discriminator from pix2pixhd, but you optimized it with a hinge loss. This looks strange to me since the multi scale discriminator outputs not the simple fake/real prediction but a feature map. So is it reasonable to optimize it with the hinge loss?

**Comment by taotaonice** [comment]
![Screenshot from 2020-04-22 11-50-47](https://user-images.githubusercontent.com/21911551/79938561-884a9380-848f-11ea-81e6-34ef7b2d25c5.png)
