### ISSUE TITLE
usage guide

### ISSUE THREAD

**Issue by mzmfarid** [taotaonice/FaceShifter#26]
Can You please send me the trained models or at least a usage guide on how to train them.

**Comment by taotaonice** [comment]
Leave your email address

**Comment by dragen1860** [comment]
dragen1860@qq.com @taotaonice  please send me the G  and D pretrained file! Thank you.

**Comment by zhangluustb** [comment]
632518615@qq.com @taotaonice @dragen1860  Thank you.please send me the G and D pretrained file!

**Comment by ketan4373** [comment]
25ketan@gmail.com  @taotaonice please send me the G and D pretrained file! Thank you.

**Comment by leonardodora** [comment]
236524279@qq.com @taotaonice 
Thank you!
please send me the G/D pretrained file and the usage guide

**Comment by LorenzoAgnolucci** [comment]
@taotaonice @mzmfarid @dragen1860 could you please send me the G and D pre-trained file to lory.agnolucci@gmail.com? Thanks in advance

**Comment by priyamanohar8** [comment]
@taotaonice @mzmfarid @dragen1860 if you still have please send me the G/D pretrained file and the usage guide
