### ISSUE TITLE
full black image as result

### ISSUE THREAD

**Issue by mzmfarid** [taotaonice/FaceShifter#27]
I am trying to run it on colab. I am saving file in stead of cv2.imshow since colab does not support that.
But it results totally in black image

**Comment by taotaonice** [comment]
Maybe should *255

**Comment by ocastan** [comment]
I confirm, I've modified this way inference_demo.py to save the generated image.

**Comment by HelloJianHan** [comment]
Using cv2.imwrite you should multiply image by 255 and it will be work.
![image](https://user-images.githubusercontent.com/25529815/82147495-1bee6480-9882-11ea-9cb4-87fbd88e8939.png)

**Comment by mozillah** [comment]
Hi @mzmfarid @taotaonice @JeyesHan @ocastan 
can anyone  share the pretrained weights with me?
my email address is mozillah0096@gmail.com.
