### ISSUE TITLE
About finetune

### ISSUE THREAD

**Issue by lishiyuwhu** [taotaonice/FaceShifter#9]
![ezgif-6-f9786f7bdf9e](https://user-images.githubusercontent.com/7754393/74243745-3a8d0e80-4d1b-11ea-8e42-433a20521549.gif)
I test your weights(only AEI-NET) and it seems great, but for Asian face the performance is not as goods as this. So I want to finetune on Asian face set. 

Should I use ` With_Identity('../washed_img/', 0.8) ` to fintune? And what's the `classes` in With_Identity()?
```
if not fine_tune_with_identity:
    dataset = FaceEmbed(['../celeb-aligned-256_0.85/', '../ffhq_256_0.85/', '../vgg_256_0.85/', '../stars_256_0.85/'], same_prob=0.3)
else:
    dataset = With_Identity('../washed_img/', 0.8)
```

**Comment by taotaonice** [comment]
> ![ezgif-6-f9786f7bdf9e](https://user-images.githubusercontent.com/7754393/74243745-3a8d0e80-4d1b-11ea-8e42-433a20521549.gif)
> I test your weights(only AEI-NET) and it seems great, but for Asian face the performance is not as goods as this. So I want to finetune on Asian face set.
> 
> Should I use `With_Identity('../washed_img/', 0.8)` to fintune? And what's the `classes` in With_Identity()?
> 
> ```
> if not fine_tune_with_identity:
>     dataset = FaceEmbed(['../celeb-aligned-256_0.85/', '../ffhq_256_0.85/', '../vgg_256_0.85/', '../stars_256_0.85/'], same_prob=0.3)
> else:
>     dataset = With_Identity('../washed_img/', 0.8)
> ```

It(With_Identity) is my try to improve the performance, but it does not work fine as I guess, so it is deprecated.
You can finetune it just like normal training process(Using FaceEmbed).

**Comment by lishiyuwhu** [comment]
> > ![ezgif-6-f9786f7bdf9e](https://user-images.githubusercontent.com/7754393/74243745-3a8d0e80-4d1b-11ea-8e42-433a20521549.gif)
> > I test your weights(only AEI-NET) and it seems great, but for Asian face the performance is not as goods as this. So I want to finetune on Asian face set.
> > Should I use `With_Identity('../washed_img/', 0.8)` to fintune? And what's the `classes` in With_Identity()?
> > ```
> > if not fine_tune_with_identity:
> >     dataset = FaceEmbed(['../celeb-aligned-256_0.85/', '../ffhq_256_0.85/', '../vgg_256_0.85/', '../stars_256_0.85/'], same_prob=0.3)
> > else:
> >     dataset = With_Identity('../washed_img/', 0.8)
> > ```
> 
> It(With_Identity) is my try to improve the performance, but it does not work fine as I guess, so it is deprecated.
> You can finetune it just like normal training process(Using FaceEmbed).

Thanks!

**Comment by leonardodora** [comment]
> ![ezgif-6-f9786f7bdf9e](https://user-images.githubusercontent.com/7754393/74243745-3a8d0e80-4d1b-11ea-8e42-433a20521549.gif)
> I test your weights(only AEI-NET) and it seems great, but for Asian face the performance is not as goods as this. So I want to finetune on Asian face set.
> 
> Should I use `With_Identity('../washed_img/', 0.8)` to fintune? And what's the `classes` in With_Identity()?
> 
> ```
> if not fine_tune_with_identity:
>     dataset = FaceEmbed(['../celeb-aligned-256_0.85/', '../ffhq_256_0.85/', '../vgg_256_0.85/', '../stars_256_0.85/'], same_prob=0.3)
> else:
>     dataset = With_Identity('../washed_img/', 0.8)
> ```

hello, i meet with the same problem as yours. 
i want to finetune with asian face, so the result of your finetune is as expected?and what dataset you use?
looking forwards to your reply!
